id: ID963D533
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:13:58+00:00'
last_modified: '2022-06-07T13:57:47.190943+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23908
  title: ལྷོ་བྲག་མཁར་ཆུ་བདུད་འཇོམས་གླིང་གི་འདོན་ཆའི་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    85F4:
      image_group_id: I3482
      title: ''
      total_pages: 1010
      order: 1
      base_file: 85F4.txt
    '7505':
      image_group_id: I3483
      title: ''
      total_pages: 972
      order: 2
      base_file: 7505.txt
    36DF:
      image_group_id: I3484
      title: ''
      total_pages: 944
      order: 3
      base_file: 36DF.txt
    '4964':
      image_group_id: I3485
      title: ''
      total_pages: 1294
      order: 4
      base_file: 4964.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
