id: P001669
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:13:36.050369
source_metadata:
  id: bdr:W23908
  title: ལྷོ་བྲག་མཁར་ཆུ་བདུད་འཇོམས་གླིང་གི་འདོན་ཆའི་སྐོར
  author: ''
  volumes:
    d2b6f8ef9ebb417a8babf87bbbd44726:
      image_group_id: I3482
      title: ''
      volume_number: 1
      total_pages: 1010
      base_file: v001.txt
    dc48d71201e44ccfbed41dd498016c4d:
      image_group_id: I3483
      title: ''
      volume_number: 2
      total_pages: 972
      base_file: v002.txt
    bf00b2052b0842fba3f83d6ebfdd5f59:
      image_group_id: I3484
      title: ''
      volume_number: 3
      total_pages: 944
      base_file: v003.txt
    7f07bf4055984f4795de3b9172e3bb33:
      image_group_id: I3485
      title: ''
      volume_number: 4
      total_pages: 1294
      base_file: v004.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
